version: 2.1
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: mule
jobs:
  build:
    docker:
      - image: 'circleci/openjdk:8-jdk'
        environment:
          MULE_VERSION: 4.3.0
          MULE_APP_NAME: test-circleci
          MULE_ENV: DEV
          MULE_WORKER_TYP: MICRO
          MULE_WORKER: 1
    steps:
      - checkout
      - run:
          name: Build
          command: |
            mvn clean compile -s settings.xml